name: Run k6 Load Test

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  k6test_1:
    name: Run k6 test 1
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: k6 Load Test
        uses: grafana/k6-action@v0.3.1
        with:
          filename: k6/workload.js

  k6test_2:
    name: Run k6 test 2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: k6 Load Test
        uses: grafana/k6-action@v0.3.1
        with:
          filename: k6/workload.js

  k6test_3:
    name: Run k6 test 3
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: k6 Load Test
        uses: grafana/k6-action@v0.3.1
        with:
          filename: k6/workload.js

  k6test_4:
    name: Run k6 test 4
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: k6 Load Test
        uses: grafana/k6-action@v0.3.1
        with:
          filename: k6/workload.js

  k6test_5:
    name: Run k6 test 5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: k6 Load Test
        uses: grafana/k6-action@v0.3.1
        with:
          filename: k6/workload.js
